//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accrual
    {
        public int Id { get; set; }
        public int ConsumptionObjectId { get; set; }
        public int PeriodMonth { get; set; }
        public int PeriodYear { get; set; }
        public decimal ConsumptionValue { get; set; }
        public int TariffId { get; set; }
        public decimal Amount { get; set; }
        public bool IsPaid { get; set; }
    
        public virtual ConsumptionObject ConsumptionObject { get; set; }
        public virtual Tariff Tariff { get; set; }
    }
}
