//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime ActionTime { get; set; }
        public string ActionType { get; set; }
        public string TableName { get; set; }
        public int RecordId { get; set; }
        public string OldValuesJson { get; set; }
        public string NewValuesJson { get; set; }
        public string IpAddress { get; set; }
    
        public virtual User User { get; set; }
    }
}
