//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int Id { get; set; }
        public string ContractNumber { get; set; }
        public int ConsumptionObjectId { get; set; }
        public System.DateTime ContractDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int ContractStatusId { get; set; }
        public int TariffId { get; set; }
    
        public virtual ConsumptionObject ConsumptionObject { get; set; }
        public virtual ContractStatus ContractStatus { get; set; }
        public virtual Tariff Tariff { get; set; }
    }
}
