//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractStatus
    {
        public ContractStatus()
        {
            this.Contract = new HashSet<Contract>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool AllowsBilling { get; set; }
    
        public virtual ICollection<Contract> Contract { get; set; }
    }
}
