//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebtProcessLog
    {
        public int Id { get; set; }
        public int ConsumptionObjectId { get; set; }
        public decimal DebtAmount { get; set; }
        public decimal TwoMonthNormAmount { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public bool NotificationSent { get; set; }
        public Nullable<System.DateTime> RestrictionDate { get; set; }
        public bool RestrictionApplied { get; set; }
        public Nullable<System.DateTime> DisconnectionDate { get; set; }
        public bool DisconnectionApplied { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual ConsumptionObject ConsumptionObject { get; set; }
    }
}
