//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnergySource
    {
        public EnergySource()
        {
            this.SupplyPoint = new HashSet<SupplyPoint>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> CapacityMW { get; set; }
    
        public virtual ICollection<SupplyPoint> SupplyPoint { get; set; }
    }
}
