//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnergyMeteringSystemEntities : DbContext
    {
        public EnergyMeteringSystemEntities()
            : base("name=EnergyMeteringSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Accrual> Accrual { get; set; }
        public DbSet<AuditLog> AuditLog { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<ConsumptionObject> ConsumptionObject { get; set; }
        public DbSet<Contract> Contract { get; set; }
        public DbSet<ContractStatus> ContractStatus { get; set; }
        public DbSet<EnergySource> EnergySource { get; set; }
        public DbSet<Meter> Meter { get; set; }
        public DbSet<MeterReading> MeterReading { get; set; }
        public DbSet<MeterReplacementHistory> MeterReplacementHistory { get; set; }
        public DbSet<MeterStatus> MeterStatus { get; set; }
        public DbSet<MeterType> MeterType { get; set; }
        public DbSet<ObjectType> ObjectType { get; set; }
        public DbSet<Payment> Payment { get; set; }
        public DbSet<PaymentMethod> PaymentMethod { get; set; }
        public DbSet<ReadingStatus> ReadingStatus { get; set; }
        public DbSet<Region> Region { get; set; }
        public DbSet<RejectionReason> RejectionReason { get; set; }
        public DbSet<Street> Street { get; set; }
        public DbSet<SupplyPoint> SupplyPoint { get; set; }
        public DbSet<SupplyPointConsumptionObject> SupplyPointConsumptionObject { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tariff> Tariff { get; set; }
        public DbSet<TariffType> TariffType { get; set; }
        public DbSet<UnitOfMeasure> UnitOfMeasure { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserRole> UserRole { get; set; }
        public DbSet<VerificationInterval> VerificationInterval { get; set; }
    }
}
