//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meter()
        {
            this.MeterReading = new HashSet<MeterReading>();
            this.MeterReplacementHistory = new HashSet<MeterReplacementHistory>();
            this.MeterReplacementHistory1 = new HashSet<MeterReplacementHistory>();
            this.MeterDataHistory = new HashSet<MeterDataHistory>();
        }
    
        public int Id { get; set; }
        public string SerialNumber { get; set; }
        public int MeterTypeId { get; set; }
        public int ConsumptionObjectId { get; set; }
        public System.DateTime InstallationDate { get; set; }
        public decimal InitialReading { get; set; }
        public int MeterStatusId { get; set; }
        public Nullable<System.DateTime> VerificationDate { get; set; }
        public Nullable<System.DateTime> NextVerificationDate { get; set; }
        public Nullable<int> ServiceLifeYears { get; set; }
        public Nullable<System.DateTime> RemovalDate { get; set; }
    
        public virtual ConsumptionObject ConsumptionObject { get; set; }
        public virtual MeterStatus MeterStatus { get; set; }
        public virtual MeterType MeterType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeterReading> MeterReading { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeterReplacementHistory> MeterReplacementHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeterReplacementHistory> MeterReplacementHistory1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeterDataHistory> MeterDataHistory { get; set; }
    }
}
