//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meter
    {
        public Meter()
        {
            this.MeterReading = new HashSet<MeterReading>();
            this.MeterReplacementHistory = new HashSet<MeterReplacementHistory>();
            this.MeterReplacementHistory1 = new HashSet<MeterReplacementHistory>();
        }
    
        public int Id { get; set; }
        public string SerialNumber { get; set; }
        public int MeterTypeId { get; set; }
        public int ConsumptionObjectId { get; set; }
        public System.DateTime InstallationDate { get; set; }
        public decimal InitialReading { get; set; }
        public int MeterStatusId { get; set; }
        public Nullable<System.DateTime> VerificationDate { get; set; }
        public Nullable<System.DateTime> NextVerificationDate { get; set; }
    
        public virtual ConsumptionObject ConsumptionObject { get; set; }
        public virtual MeterStatus MeterStatus { get; set; }
        public virtual MeterType MeterType { get; set; }
        public virtual ICollection<MeterReading> MeterReading { get; set; }
        public virtual ICollection<MeterReplacementHistory> MeterReplacementHistory { get; set; }
        public virtual ICollection<MeterReplacementHistory> MeterReplacementHistory1 { get; set; }
    }
}
