//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterType
    {
        public MeterType()
        {
            this.Meter = new HashSet<Meter>();
            this.VerificationInterval = new HashSet<VerificationInterval>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Voltage { get; set; }
        public int MaxCurrent { get; set; }
        public string AccuracyClass { get; set; }
        public int DigitCount { get; set; }
        public int DecimalPlaces { get; set; }
    
        public virtual ICollection<Meter> Meter { get; set; }
        public virtual ICollection<VerificationInterval> VerificationInterval { get; set; }
    }
}
