//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterStatus
    {
        public MeterStatus()
        {
            this.Meter = new HashSet<Meter>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool CanAcceptReadings { get; set; }
    
        public virtual ICollection<Meter> Meter { get; set; }
    }
}
