//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterDataHistory
    {
        public int Id { get; set; }
        public int MeterId { get; set; }
        public int PeriodYear { get; set; }
        public int PeriodMonth { get; set; }
        public decimal Value { get; set; }
        public string SourceType { get; set; }
        public int ChangedByUserId { get; set; }
        public System.DateTime ChangedAt { get; set; }
        public string Comment { get; set; }
    
        public virtual Meter Meter { get; set; }
        public virtual User User { get; set; }
    }
}
