//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterReplacementHistory
    {
        public int Id { get; set; }
        public int OldMeterId { get; set; }
        public int NewMeterId { get; set; }
        public int ConsumptionObjectId { get; set; }
        public System.DateTime ReplacementDate { get; set; }
        public string Reason { get; set; }
        public Nullable<decimal> LastReadingOld { get; set; }
        public Nullable<decimal> FirstReadingNew { get; set; }
    
        public virtual ConsumptionObject ConsumptionObject { get; set; }
        public virtual Meter Meter { get; set; }
        public virtual Meter Meter1 { get; set; }
    }
}
