//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterReading
    {
        public int Id { get; set; }
        public int MeterId { get; set; }
        public System.DateTime ReadingDate { get; set; }
        public decimal Value { get; set; }
        public System.DateTime EnteredAt { get; set; }
        public int EnteredByUserId { get; set; }
        public int ReadingStatusId { get; set; }
        public Nullable<int> RejectionReasonId { get; set; }
        public string Comment { get; set; }
        public int TariffZone { get; set; }
    
        public virtual Meter Meter { get; set; }
        public virtual ReadingStatus ReadingStatus { get; set; }
        public virtual RejectionReason RejectionReason { get; set; }
        public virtual User User { get; set; }
    }
}
