//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeterType()
        {
            this.Meter = new HashSet<Meter>();
            this.VerificationInterval = new HashSet<VerificationInterval>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Voltage { get; set; }
        public int MaxCurrent { get; set; }
        public string AccuracyClass { get; set; }
        public int DigitCount { get; set; }
        public int DecimalPlaces { get; set; }
        public Nullable<int> ServiceLifeYears { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meter> Meter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VerificationInterval> VerificationInterval { get; set; }
    }
}
