//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnergyMeteringSystemEntities : DbContext
    {
        public EnergyMeteringSystemEntities()
            : base("name=EnergyMeteringSystemEntities")
        {
            this.Configuration.AutoDetectChangesEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditLog> AuditLog { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<ConsumptionObject> ConsumptionObject { get; set; }
        public virtual DbSet<EnergySource> EnergySource { get; set; }
        public virtual DbSet<Meter> Meter { get; set; }
        public virtual DbSet<MeterDataHistory> MeterDataHistory { get; set; }
        public virtual DbSet<MeterReading> MeterReading { get; set; }
        public virtual DbSet<MeterReplacementHistory> MeterReplacementHistory { get; set; }
        public virtual DbSet<MeterStatus> MeterStatus { get; set; }
        public virtual DbSet<MeterType> MeterType { get; set; }
        public virtual DbSet<ObjectType> ObjectType { get; set; }
        public virtual DbSet<ReadingStatus> ReadingStatus { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<RejectionReason> RejectionReason { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<SupplyPoint> SupplyPoint { get; set; }
        public virtual DbSet<SupplyPointConsumptionObject> SupplyPointConsumptionObject { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<VerificationInterval> VerificationInterval { get; set; }
    }
}
