//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadingStatus
    {
        public ReadingStatus()
        {
            this.MeterReading = new HashSet<MeterReading>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ColorHex { get; set; }
    
        public virtual ICollection<MeterReading> MeterReading { get; set; }
    }
}
