//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Street
    {
        public Street()
        {
            this.ConsumptionObject = new HashSet<ConsumptionObject>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CityId { get; set; }
        public string PostalCode { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<ConsumptionObject> ConsumptionObject { get; set; }
    }
}
