//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyPoint
    {
        public SupplyPoint()
        {
            this.SupplyPointConsumptionObject = new HashSet<SupplyPointConsumptionObject>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int EnergySourceId { get; set; }
        public int VoltageLevel { get; set; }
        public Nullable<decimal> MaxPower { get; set; }
    
        public virtual EnergySource EnergySource { get; set; }
        public virtual ICollection<SupplyPointConsumptionObject> SupplyPointConsumptionObject { get; set; }
    }
}
