//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyPointConsumptionObject
    {
        public int SupplyPointId { get; set; }
        public int ConsumptionObjectId { get; set; }
        public System.DateTime ConnectionDate { get; set; }
        public Nullable<System.DateTime> DisconnectionDate { get; set; }
    
        public virtual ConsumptionObject ConsumptionObject { get; set; }
        public virtual SupplyPoint SupplyPoint { get; set; }
    }
}
