//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyMeteringSystem.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tariff
    {
        public Tariff()
        {
            this.Accrual = new HashSet<Accrual>();
            this.Contract = new HashSet<Contract>();
        }
    
        public int Id { get; set; }
        public int TariffTypeId { get; set; }
        public int UnitId { get; set; }
        public decimal PricePerUnit { get; set; }
        public int ZoneNumber { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<Accrual> Accrual { get; set; }
        public virtual ICollection<Contract> Contract { get; set; }
        public virtual TariffType TariffType { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
    }
}
